# Generated by Django 4.1.7 on 2023-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('root', 'Root'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=255),
        ),
    ]
