# Generated by Django 4.1.7 on 2023-05-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
