# Generated by Django 4.1.7 on 2023-05-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='house',
        ),
        migrations.AddField(
            model_name='review',
            name='address',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
