# Generated by Django 4.1.7 on 2023-05-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_review_house_review_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcategory',
            name='task_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
