# Generated by Django 4.1.7 on 2023-05-27 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_reviewsource_review_user_name_review_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='source',
        ),
        migrations.AddField(
            model_name='review',
            name='review_source',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.reviewsource'),
        ),
    ]
