# Generated by Django 4.1.7 on 2023-05-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_remove_review_source_review_review_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_source',
            new_name='source',
        ),
    ]
