# Generated by Django 4.1.7 on 2023-05-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_region_district_house_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
